### ISSUE TITLE
Ad types API not fully implemented

### ISSUE THREAD

**Issue by daveyarwood** [adzerk/adzerk-api#16]
Ad types API docs: https://github.com/adzerk/adzerk-api/wiki/Ad-Type-Endpoints

Currently with the adzerk-api gem, the ad-types endpoint just inherits from the generic API endpoint, and you can only use it to list ad types. Need to write tests for, and then implement, the other features of the ad types API (creating an ad type, listing ad types by channel, deleting an ad type, etc.)

**Comment by micha** [comment]
Fixed in 7af2ba973fdf535b91f090ed34aee106c6cae05f
