### ISSUE TITLE
No Tag or Release for version 0.6

### ISSUE THREAD

**Issue by mtowers** [adzerk/adzerk-api#19]
On June 22, the commit below included a bump in the version number for the gem from `0.5` to `0.6` but no tag or release was made.

https://github.com/adzerk/adzerk-api/commit/87c8c28fdcfe93e1fb7647a77d3233b07d6781f7

**Comment by micha** [comment]
Thanks for the heads up! Tag created. What do you mean by "release"? There is a gem deployed to rubygems.org, no?

**Comment by mtowers** [comment]
I was referring to the [GitHub Releases](https://github.com/adzerk/adzerk-api/releases) feature.  It looks like both a [0.6 tag](https://github.com/adzerk/adzerk-api/tree/0.6) and a [0.6 release](https://github.com/adzerk/adzerk-api/releases/tag/0.6) have been created.  Thanks for the help!
