### ISSUE TITLE
I should be able to get active and inactive flights without 2 separate queries

### ISSUE THREAD

**Issue by ZainVirani** [adzerk/adzerk-api#35]
Either make the default true || false or allow some option for both.

**Comment by daveyarwood** [comment]
Hi @ZainVirani,

If I'm not mistaken, the default behavior of listing flights via `client.flights` is that it should return both active and inactive flights. Is this not what you're seeing?

**Comment by ZainVirani** [comment]
@daveyarwood I'm using a GET request to adzerk.
https://github.com/adzerk/adzerk-api/wiki/Flight-Filtering-Endpoints
This document says IsActive defaults to true, and the behaviour I'm seeing matches this document.

**Comment by daveyarwood** [comment]
That should not be the case. Perhaps there is some misunderstanding about how the endpoint works? Here is an example curl request to `/v1/flight` to list all flights:

```
$ curl -s -H "X-Adzerk-ApiKey:$ADZERK_API_KEY" https://api.adzerk.net/v1/flight
```

I was able to make this request with my own network's API key, and the resulting list of flights included some active and some inactive flights.

Also, please note that the documentation you linked is outdated. Updated documentation for the "list flights" endpoint is here: https://dev.adzerk.com/reference#list-flights

I hope this is helpful... please reach out to Adzerk support if you need further assistance.

**Comment by ZainVirani** [comment]
The documentation here also says it defaults to true https://dev.adzerk.com/reference#flight-category

**Comment by daveyarwood** [comment]
Whoops! My mistake, we're talking about two different endpoints.

[**/v1/flight**](https://dev.adzerk.com/reference#list-flights) gives you a list of all of your flights (active and inactive) by default
[**/v1/fast/flight**](https://dev.adzerk.com/reference#flight-category) is a newer endpoint that gives you only active flights by default.

You are correct in that the **/v1/fast/flight** endpoint does not offer a way to get both active and inactive flights.

Sorry about the confusion there. Would you mind following up with support from here? This repo is specifically for the `adzerk` Ruby gem.
