### ISSUE TITLE
Reporting API - Status 1

### ISSUE THREAD

**Issue by tim-sauchuk** [adzerk/adzerk-api#38]
**Note**: The following was done with the requests package in Python.

---

I made a POST request to the Reporting API and successfully got a report ID. Then, I made a GET request to:
https://api.adzerk.net/v1/report/queue/{report_id}

I got back a response with status 200, but the following content:
{"Id": {report_id}, "Status": 1}

I also tried editing the URL in the Report Builder in the UI and got a valid report with the same parameters from the POST request using the following URL:
https://app.adzerk.com/#!/reports/{report_id}

The weird thing, is when I step thru my code using a debugger, I get a good result. However, when I run it straight thru and print, I see an empty response.

Am I creating the GET request incorrectly? Not sure where to go from here.

I appreciate any help!

---

**Update**: I was able to get a valid response without the debug. However, I had to run time.sleep() in order to give the GET request more time to process. I experimented with varying amounts of data, and found that the amount of time needed to wait differs greatly as well. Calling time.sleep() during production code is not something I'm comfortable doing, and I'm guessing this is due to some backend error with the Reporting API.

**Comment by nabacg** [comment]
Glad to hear you figured out a solution on your own.  Our reports are asynchronous and it's better to think of POST endpoint as enqueuing a report to be run and GET endpoint as a way to check if results are ready. The GET endpoint returns a status of running report (Status = 1 means InProgress), until the report finishes running and then it will serve your results. I'll refer to our [API docs](https://dev.adzerk.com/reference/queued-reports#poll-for-queued-report-result) for more details. 
Also, you're right reports can take various amount of time to finish, that depends on many factors, amount of data and type of data being queried being the main ones.

**Comment by tim-sauchuk** [comment]
Makes sense. I implemented a while loop with a lag to give each report time to generate.

I appreciate the quick response, and I'll reach back out with any other questions that come up :)

**Comment by karnowski** [comment]
@tim-sauchuk In the future feel free to reach out to `support@adzerk.com` !  Thanks for being our customer! :bow:
